### ISSUE TITLE
Feature request: limited number of rows

### ISSUE THREAD

**Issue by FeepingCreature** [numirias/paxmod#60] opened 2020-04-14 15:27 UTC
Thanks a lot for this extension!

Something that used to work with TabMixPlus was limiting the number of rows of tabs shown at once, and letting the user scroll up and down in the tab list. Any chance to bring this back?

**Comment by numirias** [comment] 2020-06-08 01:28
Duplicate of #46

**Closed by numirias** 2020-06-08 01:28 UTC
