### ISSUE TITLE
Addon not active on FF upstart

### ISSUE THREAD

**Issue by Dxhs** [numirias/paxmod#65] opened 2020-07-17 13:16 UTC
I'm running linux and complying with the readme.

FF 80.0a1 (2020-07-16)

When starting FF the add-on isn't doing anything until I open its preference page in about:addons, then and only afterwards  everything kicks in and works. Don't need to keep the pref page open. This doesn't happen when FF and paxmod is already running and I'm spawning a new FF window. It only happens when starting from scratch (e.g. Ctrl+Q or reboot or no firefox processes running beforehand). 

I'm happy to provide more information, but not sure what yet.

**Comment by numirias** [comment] 2020-10-19 03:16
Unfortunately, I can't reproduce this. Does the bug still occur with the most recent release?

**Comment by numirias** [comment] 2021-04-13 01:59
Since there is no update on the issue, I'll close it for now. Feel free to reopen with up-to-date information.

**Closed by numirias** 2021-04-13 01:59 UTC
