### ISSUE TITLE
Multiple rows issue

### ISSUE THREAD

**Issue by nakleng44** [numirias/paxmod#70] opened 2020-09-17 08:21 UTC
Is there a way to see all the rows and tabs like before instead of seeing just 2 rows and scroll?

**Environment**
win10, Firefox developer edition 81.0b9, Paxmod version 3.5

**Comment by jtagcat** [comment] 2020-09-18 11:27
Duplicate of #66.

**Comment by nakleng44** [comment] 2020-09-18 17:26
> Duplicate of #66.

not really

**Comment by numirias** [comment] 2020-10-19 01:54
Duplicate of #66, should be fixed in latest release. Feel free to reopen if the problem persists.

**Closed by numirias** 2020-10-19 01:54 UTC
