### ISSUE TITLE
Tab style changes

### ISSUE THREAD

**Issue by einicher** [numirias/paxmod#67] opened 2020-08-13 16:23 UTC
Ubuntu 20.04, Firefox 81, nightly

On hover and when loading - so if hidden icons of close or loading appear - the tab width is changing for the icon to fit in.

when i hover over the tab the close icon appears and tab grows a litte. When i activate "always show close button" this does not happen. When page is loading, and loader icon appears, tab width grows again, when loading is finished and loading icon disappears, tab width goes back as it was before.

This is no biggy, since it does not break functionality. It just makes it appear shaking the tabbar - makes it feel unstable.

Hard to describe, you understand what I mean?

**Comment by numirias** [comment] 2020-10-19 01:56
I think this was caused by #66 which is fixed in the latest release. Feel free to reopen if the problem persists.

**Closed by numirias** 2020-10-19 01:56 UTC
