### ISSUE TITLE
Transparent Tabs on Windows 10 with 65.01b

### ISSUE THREAD

**Issue by olaims** [numirias/paxmod#26] opened 2018-12-05 19:20 UTC
I'm having some strange transparent tabs after an automatically update was done,

![image](https://user-images.githubusercontent.com/27026293/49538203-2950a280-f8cb-11e8-83ac-e073f5312f84.png)

![image](https://user-images.githubusercontent.com/27026293/49538113-fc03f480-f8ca-11e8-91b3-3a66be621729.png)

**Comment by b1czu** [comment] 2018-12-07 12:36
Same here on Windows and Antergos Linux. Affected version FF Dev 65.0b1.

**Comment by numirias** [comment] 2018-12-08 02:34
Thanks for reporting to both of you. I'm hoping to find some time to look into it this weekend. If you have capabilities to investigate the issue yourself, please go ahead.

**Comment by Veritogen** [comment] 2018-12-08 12:58
For me it looks like that after using the setting that I mentioned in #25 .

**Comment by b1czu** [comment] 2018-12-12 11:39
Commenting out these titlebar attributes fixes it for FF65+.
`/*#titlebar {
    visibility: var(--paxmod-titlebar-visibility);
    height: var(--tab-min-height) !important;
    margin-bottom: calc(0px - var(--tab-min-height)) !important;
}*/

/*#main-window[sizemode="maximized"] #titlebar {
    margin-bottom:calc(var(--paxmod-titlebar-margin) - var(--tab-min-height)) !important;
}*/

/*#main-window[sizemode="normal"] > #titlebar {
    display: var(--paxmod-titlebar-display);
}*/`
I don't know how to do this without breaking FF64- so I'm not issuing a pull request.

**Comment by Veritogen** [comment] 2018-12-13 19:15
Works like a charm! Thanks a lot!

**Comment by numirias** [comment] 2018-12-14 06:57
Seems like a duplicate of #25

**Closed by numirias** 2018-12-14 06:57 UTC
Labels: duplicate
