### ISSUE TITLE
Max. number of tab rows not working

### ISSUE THREAD

**Issue by 090media** [numirias/paxmod#71] opened 2020-09-23 17:04 UTC
Just updated to 3.5. Set "Max. number of tab rows" to 5 and hit APPLY. Restarted FF. Still see ten rows of tabs. No scrollbar. Everything else works fine. Did I miss a step here?

Windows 10 Pro 1909 / FF Developer 73.0b2 / Paxmod 3.5

**Comment by numirias** [comment] 2020-10-19 01:53
Duplicate of #66, should be fixed in latest release!

**Comment by 090media** [comment] 2020-10-19 07:45
I'm not sure this is a duplicate. All of my tabs were showing up. I just can't limit the number of rows. Still can't, after upgrading to v3.6. See attached screenshot. Thanks!
![Screenshot](https://user-images.githubusercontent.com/48948131/96416107-6d3daf80-11a4-11eb-908f-6c6dbada0c1e.jpg)

**Comment by numirias** [comment] 2020-10-20 12:41
Thanks for the update. Which version of FF developer are you running at the moment?

**Comment by numirias** [comment] 2021-04-13 01:57
Since there are no updates on the bug report and the latest version doesn't seem to have any problems with the max. number of tab rows, I'll close this for now.

**Closed by numirias** 2021-04-13 01:57 UTC
