### ISSUE TITLE
+ Open new Tab is not being displayed

### ISSUE THREAD

**Issue by olaims** [numirias/paxmod#35] opened 2019-04-29 22:04 UTC
Hello, I have the firefox version 67.0b14 (64-bit) and I've noticed that the "+" for opening new tabs has "disappeared".

I've tried changing some settings on the customize menu, but without any success. 

![image](https://user-images.githubusercontent.com/27026293/56929975-8e579f80-6adb-11e9-8b4f-e7ea68b6a209.png)

**Comment by numirias** [comment] 2019-05-30 18:52
Thanks for reporting. Unfortunately I can't reproduce the bug since the settings works fine for me in lastest FF Developer on Windows and Linux.

Are you sure the box *Display new tab button* under *about:addons > Preferences > Paxmod* is checked?

**Comment by numirias** [comment] 2019-08-14 11:31
Closing for now. Feel free to reopen if the problem persists.

**Closed by numirias** 2019-08-14 11:31 UTC

**Comment by bentran** [comment] 2020-02-02 12:43
I just installed Paxmod and cannot see the new tab button. Firefox dev editon 73.0b12 (64 bits). 

The only way I seem to be able to open a new tab is to press Ctrl + T

**Comment by numirias** [comment] 2020-02-02 20:28
> I just installed Paxmod and cannot see the new tab button. Firefox dev editon 73.0b12 (64 bits).

@bentran Could you confirm:

> Are you sure the box _Display new tab button_ under _about:addons > Preferences > Paxmod_ is checked?

**Comment by bentran** [comment] 2020-02-03 13:00
> > Are you sure the box _Display new tab button_ under _about:addons > Preferences > Paxmod_ is checked?

Ahh that was I was missing!  Didn't even know there was options to set. Thank you.
