### ISSUE TITLE
Scroll in tab bar

### ISSUE THREAD

**Issue by Djagga-Djagga** [numirias/paxmod#69] opened 2020-09-04 08:54 UTC
Hello my friend.

Since last update Firefox limited visual lines in tabbar to two rows. In case of opening a lot of tabs scrollbar appears.
Like this
https://prnt.sc/ubdv3v

As far as I keep 5 lines of tabs opened - this is very uncomfortable to use.

Looking forward for a solution!

**Comment by jtagcat** [comment] 2020-09-04 19:42
Duplicate of #66

**Comment by numirias** [comment] 2020-10-19 01:55
Duplicate of #66, should be fixed in latest release. Feel free to reopen if the problem persists.

**Closed by numirias** 2020-10-19 01:55 UTC
